In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [5]:
#creating a numpy array 
lst = [1,2,3,4,55,66,77,77]
arr = np.array(lst)
print(arr)

my_array = np.array([4,3,424,3433434])
print(my_array)

[ 1  2  3  4 55 66 77 77]
[      4       3     424 3433434]


In [6]:
"""
size comparsion of ndarray and list objects 
"""

from sys import getsizeof

lst= [1]
print(getsizeof(lst)) # 56 -> 64: int + object meta info.

arr= np.array(lst)
print(getsizeof(arr)) # 96 -> 100: int(4bytes)

64
108


In [20]:
""" 
exercise : test score
"""
test_1 = np.array([92,94,88,91,87])
test_2 = np.array([79,100,86,93,91])
test_3 = np.array([87,85,72,90,92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1],test_1[2]])
print(manual_adwoa_test_1)

student_scores = np.array([test_1,test_2,test_3])
print(student_scores)

print(student_scores[2,0])

print(student_scores[:,4])  # 4 -> -1 도 가능하다. -1은 리스트 뒤에서부터 불러옴 

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [25]:
"""
logical operations with array
"""
#원소별로 논리식에 대한 bool값을 계산
a= np.array([10,2,2,4,5,6,7,8,9,9,7,11])
mask = a>5 
print(mask)

#논리식을 만족하는 부분집합만 출력 = selection
selected = a[a>5]
print(selected)
#논리식 결합 
selected = a[(a>5)|(a<3)]
print(selected)
selected = a[(a>6)&(a<9)]
print(selected)

[ True False False False False  True  True  True  True  True  True  True]
[10  6  7  8  9  9  7 11]
[10  2  2  6  7  8  9  9  7 11]
[7 8 7]


In [29]:
"""
goldilocks porridge festival 
"""
porridge = np.array([79,65,50,63,56,90,85,98,79,51])
print(porridge)

cold = porridge[porridge < 60]
print(cold)
hot = porridge[porridge > 80]
print(hot)
just_right = porridge[(porridge>=60)&(porridge<=80)]
print(just_right)

[79 65 50 63 56 90 85 98 79 51]
[50 56 51]
[90 85 98]
[79 65 63 79]
