In [1]:
import numpy as np

In [5]:
"""
broadcasting
"""
#1D array + 2D array

x = np.ones((3,3))
print(x)
y = np.arange(3)
print(y)
print(x+y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [7]:
#broadcast both arrays
a = np.arange(3)
print(a)
a = a[:,np.newaxis]
print(a)
b = np.arange(3)

print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [13]:
"""
broadcasting rules 
"""
#1d array + 2d array
a = np.ones((2,3))
b = np.arange(3)

print(a+b,'\n')

#broadcasting both arrays
c = np.arange(3)
c = c.reshape((3,1))
d = np.arange(3)

print(c+d,'\n')

#incompatible case
#a= np.ones((3,2))
#b= np.arange(3)
# 이 경우 규칙2 적용 불가능함 -> 오류 

[[1. 2. 3.]
 [1. 2. 3.]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]] /n


In [14]:
#recap :comparison operators
x = np.array([1,2,3,4,5])
print(x)

print(x<3)
print(x>=3)
print(x!=3)
print(x==3)

[1 2 3 4 5]
[ True  True False False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [16]:
#ufuns for comparison operations
np.random.seed(0)
x = np.random.randint(10, size=(3,4))
print(x)
x<6

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [19]:
#boolean logic
#boolean 의 정수표현 : true =1, false=0
print(np.count_nonzero(x<6))
print(np.sum(x<6))

print(np.any(x>8))
print(np.all(x>1))

8
8
True
False


In [20]:
#masking operation 
print(x<5)

print(x[x<5])

[[False  True  True  True]
 [False False  True False]
 [ True  True False False]]
[0 3 3 3 2 4]


In [22]:
#fancy indexing 
np.random.seed(0)
x= np.random.randint(100, size =10)
ind = [2,4,6]
print(x[ind])

[64 67 83]


In [24]:
np.random.seed(0)
x=np.random.randint(10, size =15).reshape(3,5)
print(x)
row = [0,1,2]
col = [2,1,4]
x[row,col]

row = np.array([0,1,2])
col = np.array([2,1,4])
x[row[:, np.newaxis], col]

[[5 0 3 3 7]
 [9 3 5 2 4]
 [7 6 8 8 1]]


array([[3, 0, 7],
       [5, 3, 4],
       [8, 6, 1]])

In [25]:
#combined indexing
x = np.arange(1,13).reshape(3,4)
#기본 인덱싱 + 팬시 인덱싱
print(x[2,[2,0,1]])
#슬라이싱 + 팬시 인덱싱
print(x[2:, [2,0,1]])


[11  9 10]
[[11  9 10]]


In [29]:
"""
Exercise) Selecting random points
"""
mean = [0,0]
cov = [[1,2],
      [2,5]]
rand = np.random.RandomState(1)
rand.multivariate_normal(mean, cov, 100)
print(x)
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
